# SPDX-FileCopyrightText: 2025 hazzuk
#
# SPDX-License-Identifier: AGPL-3.0-only

---

- name: Down compose stack {{ stack }}
  become: true
  become_user: dockeruser
  tags: down
  community.docker.docker_compose_v2:
    docker_host: unix:///run/user/1001/docker.sock
    project_src: "/srv/docker/{{ stack }}"
    state: absent # docker compose down
